添加修改golang版本功能

diff --git a/.github/action/planning/action.yml b/.github/action/planning/action.yml
--- a/.github/action/planning/action.yml
+++ b/.github/action/planning/action.yml
@@ -49,6 +49,9 @@ runs:
               elif [ "$(grep -c "^zonename=" $GITHUB_WORKSPACE/config/$i/OpenWrt-K/openwrtext.config)" -eq 0 ];then
                 echo "::error ::无法获取$i配置中openwrt的时区区域名称(在OpenWrt-K/openwrtext.config中),请尝试使用新版OpenWrt-k配置构建工具"
                 exit 1
+              elif [ "$(grep -c "^golang_version=" $GITHUB_WORKSPACE/config/$i/OpenWrt-K/openwrtext.config)" -eq 0 ];then
+                echo "::error ::无法获取$i配置中openwrt的golang版本配置(在OpenWrt-K/openwrtext.config中),请尝试使用新版OpenWrt-k配置构建工具"
+                exit 1
               fi
               if [ -z "$(sed -n '/^kmod_compile_exclude_list=/p' $GITHUB_WORKSPACE/config/$i/OpenWrt-K/compile.config | sed -e "s/=[my]\([,]\{0,1\}\)/\1/g" -e 's/.*=//')" ];then
                 echo "::warning ::无法获取$i配置中的kmod编译排除列表，这很有可能导致编译失败。"
