工作流：添加提示信息

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -58,6 +58,7 @@ jobs:
         run: |
           sudo timedatectl set-timezone "Asia/Shanghai"
           echo starttime=$(date +"%y.%m.%d-%H") >> "$GITHUB_OUTPUT"
+          echo "::notice ::编译开始时间$starttime"
 
       - name: 准备环境
         run: |
@@ -241,7 +242,8 @@ jobs:
           make defconfig
           echo target=$(sed -n '/CONFIG_TARGET_BOARD/p' .config | sed -e 's/CONFIG_TARGET_BOARD\=\"//' -e 's/\"//') >> "$GITHUB_OUTPUT"
           echo subtarget=$(sed -n '/CONFIG_TARGET_SUBTARGET/p' .config | sed -e 's/CONFIG_TARGET_SUBTARGET\=\"//' -e 's/\"//') >> "$GITHUB_OUTPUT"
-  
+          echo "::notice ::你编译的架构为$target，子架构为$subtarget"
+
   build1:
     runs-on: ubuntu-22.04
     needs: prepare
@@ -323,7 +325,9 @@ jobs:
           
       - name: 切换标签/分支
         working-directory: ${{ env.OPENWRT_ROOT_PATH }}
-        run: git checkout $(sed -n '/openwrt_tag\/branche/p' $GITHUB_WORKSPACE/OpenWrt-K.Config | sed -e 's/.*=//')
+        run: |
+          git checkout $(sed -n '/openwrt_tag\/branche/p' $GITHUB_WORKSPACE/OpenWrt-K.Config | sed -e 's/.*=//')
+          echo "::notice ::你编译的标签/分支为$(sed -n '/openwrt_tag\/branche/p' $GITHUB_WORKSPACE/OpenWrt-K.Config | sed -e 's/.*=//')"
 
       - name: 复制cmzj_package
         working-directory: ${{ env.WORKSPACE_ROOT_PATH }}
@@ -390,6 +394,7 @@ jobs:
           echo 'Compiled by' $compiler
           sed -i "s/Compiled by 沉默の金/Compiled by $compiler/g" $OPENWRT_ROOT_PATH/files/etc/uci-defaults/zzz-chenmozhijin
           cat $OPENWRT_ROOT_PATH/files/etc/uci-defaults/zzz-chenmozhijin | grep 'Compiled by'
+          echo "::notice ::编译者已替换为$compiler"
           #添加编译信息
           export OPENWRT_TAG_BRANCHE="$(sed -n '/openwrt_tag\/branche/p' $GITHUB_WORKSPACE/OpenWrt-K.Config | sed -e 's/.*=//')"
           echo "COMPILE_START_TIME=\"${{ needs.prepare.outputs.starttime }}\"" >> $OPENWRT_ROOT_PATH/files/etc/openwrt-k_info
@@ -420,36 +425,36 @@ jobs:
           kernel_version="$(sed -n '/CONFIG_LINUX_/p' $OPENWRT_ROOT_PATH/.config | sed -e 's/CONFIG_LINUX_//' -e 's/=y//' -e 's/_/./g')"
           echo kernel_version=$kernel_version
           if [ "$(grep -c "^CONFIG_PACKAGE_luci-app-turboacc_INCLUDE_SHORTCUT_FE_DRV=y$" $OPENWRT_ROOT_PATH/.config)" -ne '0' ] || [ "$(grep -c "^CONFIG_PACKAGE_kmod-shortcut-fe-drv=y$" $OPENWRT_ROOT_PATH/.config)" -ne '0' ];then
-            echo "检测到sfe设为编译进固件"
+            echo "::notice ::检测到sfe设为编译进固件"
             sfe=true
           elif [ "$(grep -c "^CONFIG_PACKAGE_luci-app-turboacc_INCLUDE_SHORTCUT_FE_CM=y$" $OPENWRT_ROOT_PATH/.config)" -ne '0' ] || [ "$(grep -c "^CONFIG_PACKAGE_kmod-shortcut-fe-cm=y$" $OPENWRT_ROOT_PATH/.config)" -ne '0' ];then
-            echo "检测到sfe设为编译进固件"
+            echo "::notice ::检测到sfe设为编译进固件"
             sfe=true
           elif [ "$(grep -c "^CONFIG_PACKAGE_luci-app-turboacc_INCLUDE_SHORTCUT_FE=y$" $OPENWRT_ROOT_PATH/.config)" -ne '0' ] || [ "$(grep -c "^CONFIG_PACKAGE_kmod-fast-classifier=y$" $OPENWRT_ROOT_PATH/.config)" -ne '0' ];then
-            echo "检测到sfe设为编译进固件"
+            echo "::notice ::检测到sfe设为编译进固件"
             sfe=true
           elif [ "$(grep -c "^CONFIG_PACKAGE_kmod-shortcut-fe=y$" $OPENWRT_ROOT_PATH/.config)" -ne '0' ];then
-            echo "检测到sfe设为编译进固件"
+            echo "::notice ::检测到sfe设为编译进固件"
             sfe=true
           else
-            echo "未检测到sfe设为编译进固件"
+            echo "::notice ::未检测到sfe设为编译进固件"
             sfe=false
           fi
           if [ $sfe = true ];then
-            echo "添加sfe所需补丁与附加内核配置"
+            echo "::notice ::添加sfe所需补丁与附加内核配置"
             cp -f $CMZJ_PATCH_ROOT_PATH/hack-$kernel_version/953-net-patch-linux-kernel-to-support-shortcut-fe.patch ./target/linux/generic/hack-$kernel_version/953-net-patch-linux-kernel-to-support-shortcut-fe.patch
             cp -f $CMZJ_PATCH_ROOT_PATH/pending-$kernel_version/613-netfilter_optional_tcp_window_check.patch ./target/linux/generic/pending-$kernel_version/613-netfilter_optional_tcp_window_check.patch
             echo "#  CONFIG_SHORTCUT_FE is not set" >> $OPENWRT_ROOT_PATH/target/linux/generic/config-$kernel_version
           fi          
           if [ $sfe = true ] || [ "$(grep -c "^CONFIG_PACKAGE_kmod-nft-fullcone=y$" $OPENWRT_ROOT_PATH/.config)" -ne '0' ] || [ "$(grep -c "^CONFIG_PACKAGE_luci-app-turboacc_INCLUDE_NFT_FULLCONE=y$" $OPENWRT_ROOT_PATH/.config)" -ne '0' ];then
             if  [ "$kernel_version" = "6.1" ] || [ "$kernel_version" = "5.15" ]; then
-              echo "添加sfe/fullcone所需补丁与附加内核配置"
+              echo "::notice ::添加sfe/fullcone所需补丁与附加内核配置"
               cp $CMZJ_PATCH_ROOT_PATH/hack-$kernel_version/952-add-net-conntrack-events-support-multiple-registrant.patch $OPENWRT_ROOT_PATH/target/linux/generic/hack-$kernel_version
             elif [ "$kernel_version" = "5.10" ] ; then
-              echo "添加sfe/fullcone所需补丁与附加内核配置(5.10内核)"
+              echo "::notice ::添加sfe/fullcone所需补丁与附加内核配置(5.10内核)"
               cp $CMZJ_PATCH_ROOT_PATH/hack-$kernel_version/952-net-conntrack-events-support-multiple-registrant.patch  $OPENWRT_ROOT_PATH/target/linux/generic/hack-$kernel_version
             else
-              echo "OpenWrt-K不支持为5.10以下内核打补丁，如需编译请删除此步骤与turboacc的相关的步骤"
+              echo "::error ::OpenWrt-K不支持为5.10以下内核打补丁，如需编译请删除此步骤与turboacc的相关的步骤"
               exti 1
             fi
             echo "#  CONFIG_NF_CONNTRACK_CHAIN_EVENTS is not set" >> $OPENWRT_ROOT_PATH/target/linux/generic/config-$kernel_version
@@ -463,7 +468,7 @@ jobs:
           if [ "$(grep -c "^CONFIG_PACKAGE_kmod-nft-fullcone=y$" $OPENWRT_ROOT_PATH/.config)" -ne '0' ] || [ "$(grep -c "^CONFIG_PACKAGE_luci-app-turboacc_INCLUDE_NFT_FULLCONE=y$" $OPENWRT_ROOT_PATH/.config)" -ne '0' ];then
             kernel_version="$(sed -n '/CONFIG_LINUX_/p' $OPENWRT_ROOT_PATH/.config | sed -e 's/CONFIG_LINUX_//' -e 's/=y//' -e 's/_/./g')"
             echo kernel_version=$kernel_version
-            echo "添加fullcone所需libnftnl、firewall4、nftables补丁"
+            echo "::notice ::检测到nft-fullcone设为编译进固件,添加fullcone所需libnftnl、firewall4、nftables补丁"
             rm -rf $OPENWRT_ROOT_PATH/package/libs/libnftnl
             rm -rf $OPENWRT_ROOT_PATH/package/network/config/firewall4
             rm -rf $OPENWRT_ROOT_PATH/package/network/utils/nftables
@@ -488,7 +493,7 @@ jobs:
             echo "nftables-patches" >> $LOG_PATH/cmzj_patch.log
             ls $OPENWRT_ROOT_PATH/package/network/utils/nftables/patches/ >> $LOG_PATH/cmzj_patch.log
           else
-            echo 检测到nft-fullcone设为编译进固件,跳过添加。"
+            echo "::notice ::未检测到nft-fullcone设为编译进固件,跳过添加。"
           fi
 
       - name: 为openwrt-22.03/v22.03.*升级dnsmasq与libubox
@@ -496,7 +501,7 @@ jobs:
         run: |
           openwrt_tag_branche=$(sed -n '/openwrt_tag\/branche/p' $GITHUB_WORKSPACE/OpenWrt-K.Config | sed -e 's/.*=//')
           if [ "$openwrt_tag_branche" = "openwrt-22.03" ] || [[ "$openwrt_tag_branche" =~ ^v22.03.* ]] ; then
-            echo "升级dnsmasq与libubox"
+            echo "::notice ::检测到openwrt-22.03分支/v22.03.*版本升级dnsmasq与libubox"
             rm -rf $OPENWRT_ROOT_PATH/package/network/services/dnsmasq
             rm -rf $OPENWRT_ROOT_PATH/package/libs/libubox
             mkdir -p $OPENWRT_ROOT_PATH/package/libs/libubox
@@ -504,8 +509,21 @@ jobs:
             cp -RT $CMZJ_PATCH_ROOT_PATH/libubox $OPENWRT_ROOT_PATH/package/libs/libubox
             cp -RT $CMZJ_PATCH_ROOT_PATH/dnsmasq $OPENWRT_ROOT_PATH/package/network/services/dnsmasq
           else
-            echo "非openwrt-22.03分支/v22.03.*版本,跳过升级。"
+            echo "::notice ::检测到非openwrt-22.03分支/v22.03.*版本,跳过升级。"
           fi
+
+      - name: 检查到软件包依赖
+        working-directory: ${{ env.OPENWRT_ROOT_PATH }}
+        run: |
+          TMPDIR=$(mktemp -d) || exit 1
+          PACKAGEDEPWARNING=$TMPDIR/packagedepwarning.log
+          gmake -s prepare-tmpinfo
+          ./scripts/package-metadata.pl mk tmp/.packageinfo > tmp/.packagedeps 2>$PACKAGEDEPWARNING || { rm -f tmp/.packagedeps; false; } 
+          if [ -n "$(cat $PACKAGEDEPWARNING)" ]; then
+            echo "::error ::检查到软件包依赖问题,这极有可能导致编译错误，请前往build1检查到软件包依赖步骤查看详情。"
+            cat $PACKAGEDEPWARNING
+          fi
+          [[ -d $TMPDIR ]] && rm -rf "$TMPDIR"
 
       - name: 下载AdGuardHome核心与DNS名单
         working-directory: ${{ env.OPENWRT_ROOT_PATH }}
@@ -565,7 +583,7 @@ jobs:
               ;;
               esac
               if [ "$Arch" != 1 ];then
-                echo AdGuardHome架构为$Arch,开始下载AdGuardHome
+                echo "::notice ::检测到luci-app-adguardhome配置为编译进固件,AdGuardHome架构为$Arch开始下载"
                 mkdir -p ./files/usr/bin/AdGuardHome/tmp
                 rm -rf ./files/usr/bin/AdGuardHome/tmp/*
                 latest_ver="$(curl -s https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest 2>/dev/null|grep -E 'tag_name' |grep -E 'v[0-9.]+' -o 2>/dev/null)"
@@ -629,11 +647,11 @@ jobs:
                 echo "files"
                 ls -la $(find $OPENWRT_ROOT_PATH/files/ -type d)
               else
-                echo "AdGuardHome核心不支持此架构,退出执行。"
+                echo "::warning ::AdGuardHome核心不支持此架构,退出执行下载AdGuardHome核心与DNS名单。"
                 rm -rf $OPENWRT_ROOT_PATH/files/etc/AdGuardHome-dnslist\(by\ cmzj\).yaml $OPENWRT_ROOT_PATH/files/etc/AdGuardHome.yaml $OPENWRT_ROOT_PATH/files/AdGuardHome
               fi
           else
-            echo "未检测到luci-app-adguardhome配置为编译进固件,退出执行。"
+            echo "::notice ::未检测到luci-app-adguardhome配置为编译进固件,退出执行。"
             rm -rf $OPENWRT_ROOT_PATH/files/etc/AdGuardHome-dnslist\(by\ cmzj\).yaml $OPENWRT_ROOT_PATH/files/etc/AdGuardHome.yaml $OPENWRT_ROOT_PATH/files/AdGuardHome
           fi
           
@@ -709,11 +727,11 @@ jobs:
                 echo "files"
                 ls -la $(find $OPENWRT_ROOT_PATH/files/ -type d)
               else
-                echo openclash内核不支持此架构,退出执行。
+                echo "::warning ::openclash内核不支持此架构,退出执行下载openclash内核。"
                 rm -rf $OPENWRT_ROOT_PATH/files/etc/openclash
               fi
           else
-            echo "未检测到luci-app-openclash配置为编译进固件,退出执行。"
+            echo "::notice ::未检测到luci-app-openclash配置为编译进固件,退出执行下载openclash内核。"
             rm -rf $OPENWRT_ROOT_PATH/files/etc/openclash
           fi
           
